# Generated by Django 2.1.5 on 2019-01-26 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='analysis',
            field=models.CharField(default='Null', max_length=8192, unique=True),
        ),
    ]
